#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

cookbook 'apache2', '>= 2.0.0'
cookbook 'monit', '~> 0.7.5'
cookbook 'nvm', '~> 0.1.0'
cookbook 'git', '~> 4.0.2'
cookbook 'build-essential', '~> 2.1.2'
cookbook 'phantomjs', '~> 1.0.3'


cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'

cookbook 'postgresql',
   :git => 'https://github.com/findsyou/cookbooks',
   :ref => 'postgresql-improvements'
