#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

cookbook 'git', '~> 4.0.2'
cookbook 'build-essential', '~> 2.1.2'
cookbook 'nvm', '~> 0.1.0'
cookbook 'apache2', '>= 2.0.0'
cookbook 'phantomjs', '~> 1.0.3'
